export const CARD_TYPES = {
   TEXT: 'text',
   IMAGE: 'image',
}

export const TWELVE_CARDS_DEFAULT_DATA = [
   {
      type: 'text',
      content: '1',
      keyForMatching: '3214234QEWR',
      objectId: 'exampleId1',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '1',
      keyForMatching: '3214234QEWR',
      objectId: 'exampleId2',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '2',
      keyForMatching: 'bv524ctewr',
      objectId: 'exampleId3',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '2',
      keyForMatching: 'bv524ctewr',
      objectId: 'exampleId4',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '3',
      keyForMatching: '53213cdsa',
      objectId: 'exampleId5',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '3',
      keyForMatching: '53213cdsa',
      objectId: 'exampleId6',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '4',
      keyForMatching: 'b452d4fd',
      objectId: 'exampleId7',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '4',
      keyForMatching: 'b452d4fd',
      objectId: 'exampleId8',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '5',
      keyForMatching: 'buktv42ce',
      objectId: 'exampleId9',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '5',
      keyForMatching: 'buktv42ce',
      objectId: 'exampleId10',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '6',
      keyForMatching: 'moiuhdcctw',
      objectId: 'exampleId11',
      isFlippedToBack: true,
   },
   {
      type: 'text',
      content: '6',
      keyForMatching: 'moiuhdcctw',
      objectId: 'exampleId12',
      isFlippedToBack: true,
   },
]
